In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline

In [2]:
df=pd.read_csv("index_name_titanic.csv")

In [3]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [4]:
titanic_df=df[["Survived","Pclass","Sex","Age","SibSp","Parch","Fare","Embarked"]]

In [6]:
titanic_df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [9]:
x=titanic_df.drop("Survived",axis=1)
y=titanic_df[["Survived"]]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [11]:
x_train

     Pclass     Sex   Age  SibSp  Parch      Fare Embarked
331       1    male  45.5      0      0   28.5000        S
733       2    male  23.0      0      0   13.0000        S
382       3    male  32.0      0      0    7.9250        S
704       3    male  26.0      1      0    7.8542        S
813       3  female   6.0      4      2   31.2750        S
..      ...     ...   ...    ...    ...       ...      ...
106       3  female  21.0      0      0    7.6500        S
270       1    male   NaN      0      0   31.0000        S
860       3    male  41.0      2      0   14.1083        S
435       1  female  14.0      1      2  120.0000        S
102       1    male  21.0      0      1   77.2875        S

[712 rows x 7 columns]

In [13]:
y_train

     Survived
331         0
733         0
382         0
704         0
813         0
..        ...
106         1
270         0
860         0
435         1
102         0

[712 rows x 1 columns]

In [14]:
trf1=ColumnTransformer([("age_imp",SimpleImputer(),["Age"]),
                        ("embarked_imp",SimpleImputer(strategy="most_frequent"),["Embarked"])],remainder="passthrough")

In [16]:
trf2=ColumnTransformer([("ohe_sex_embark",OneHotEncoder(sparse_output=False,handle_unknown="ignore"),["Sex","Embarked"])],remainder="passthrough")

In [18]:
pipe=Pipeline([("trf1",trf1),("trf2",trf2)])

In [20]:
pipe.fit_transform(x_train)

ValueError: Specifying the columns using strings is only supported for dataframes.

In [21]:
trf1=ColumnTransformer([("age_imp",SimpleImputer(),["Age"]),
                        ("embarked_imp",SimpleImputer(strategy="most_frequent"),["Embarked"])],remainder="passthrough")

In [23]:
trf1.set_output(transform="pandas")

ColumnTransformer(remainder='passthrough',
                  transformers=[('age_imp', SimpleImputer(), ['Age']),
                                ('embarked_imp',
                                 SimpleImputer(strategy='most_frequent'),
                                 ['Embarked'])])

In [24]:
trf2=ColumnTransformer([("ohe_sex_embark",OneHotEncoder(sparse_output=False,handle_unknown="ignore"),["Sex","Embarked"])],remainder="passthrough")

In [25]:
pipe=Pipeline([("trf1",trf1),("trf2",trf2)])

In [26]:
pipe.fit_transform(x_train)

ValueError: A given column is not a column of the dataframe

In [32]:
trf1=ColumnTransformer([("age_imp",SimpleImputer(),["Age"]),
                        ("embarked_imp",SimpleImputer(strategy="most_frequent"),["Embarked"])],remainder="passthrough")

In [33]:
trf1.set_output(transform="pandas")

ColumnTransformer(remainder='passthrough',
                  transformers=[('age_imp', SimpleImputer(), ['Age']),
                                ('embarked_imp',
                                 SimpleImputer(strategy='most_frequent'),
                                 ['Embarked'])])

In [34]:
trf1.fit_transform(x_train)

,age_imp__Age,embarked_imp__Embarked,remainder__Pclass,remainder__Sex,remainder__SibSp,remainder__Parch,remainder__Fare
331,45.500000,S,1,male,0,0,28.5000
733,23.000000,S,2,male,0,0,13.0000
382,32.000000,S,3,male,0,0,7.9250
704,26.000000,S,3,male,1,0,7.8542
813,6.000000,S,3,female,4,2,31.2750
...,...,...,...,...,...,...,...
106,21.000000,S,3,female,0,0,7.6500
270,29.498846,S,1,male,0,0,31.0000
860,41.000000,S,3,male,2,0,14.1083
435,14.000000,S,1,female,1,2,120.0000
102,21.000000,S,1,male,0,1,77.2875

In [36]:
trf2=ColumnTransformer([("ohe_embark_sex",OneHotEncoder(sparse_output=False,handle_unknown="ignore"),["embarked_imp__Embarked","remainder__Sex"])],remainder="passthrough")

In [38]:
pipe=Pipeline([("trf1",trf1),("trf2",trf2)])

In [40]:
pipe.fit_transform(x_train)

array([[  0.    ,   0.    ,   1.    , ...,   0.    ,   0.    ,  28.5   ],
       [  0.    ,   0.    ,   1.    , ...,   0.    ,   0.    ,  13.    ],
       [  0.    ,   0.    ,   1.    , ...,   0.    ,   0.    ,   7.925 ],
       ...,
       [  0.    ,   0.    ,   1.    , ...,   2.    ,   0.    ,  14.1083],
       [  0.    ,   0.    ,   1.    , ...,   1.    ,   2.    , 120.    ],
       [  0.    ,   0.    ,   1.    , ...,   0.    ,   1.    ,  77.2875]],
      shape=(712, 10))

In [42]:
pipe.get_feature_names_out()

array(['ohe_embark_sex__embarked_imp__Embarked_C',
       'ohe_embark_sex__embarked_imp__Embarked_Q',
       'ohe_embark_sex__embarked_imp__Embarked_S',
       'ohe_embark_sex__remainder__Sex_female',
       'ohe_embark_sex__remainder__Sex_male', 'remainder__age_imp__Age',
       'remainder__remainder__Pclass', 'remainder__remainder__SibSp',
       'remainder__remainder__Parch', 'remainder__remainder__Fare'],
      dtype=object)

In [43]:
pd.DataFrame(pipe.fit_transform(x_train),columns=pipe.get_feature_names_out(),index=x_train.index)

,ohe_embark_sex__embarked_imp__Embarked_C,ohe_embark_sex__embarked_imp__Embarked_Q,ohe_embark_sex__embarked_imp__Embarked_S,ohe_embark_sex__remainder__Sex_female,ohe_embark_sex__remainder__Sex_male,remainder__age_imp__Age,remainder__remainder__Pclass,remainder__remainder__SibSp,remainder__remainder__Parch,remainder__remainder__Fare
331,0.0,0.0,1.0,0.0,1.0,45.500000,1.0,0.0,0.0,28.5000
733,0.0,0.0,1.0,0.0,1.0,23.000000,2.0,0.0,0.0,13.0000
382,0.0,0.0,1.0,0.0,1.0,32.000000,3.0,0.0,0.0,7.9250
704,0.0,0.0,1.0,0.0,1.0,26.000000,3.0,1.0,0.0,7.8542
813,0.0,0.0,1.0,1.0,0.0,6.000000,3.0,4.0,2.0,31.2750
...,...,...,...,...,...,...,...,...,...,...
106,0.0,0.0,1.0,1.0,0.0,21.000000,3.0,0.0,0.0,7.6500
270,0.0,0.0,1.0,0.0,1.0,29.498846,1.0,0.0,0.0,31.0000
860,0.0,0.0,1.0,0.0,1.0,41.000000,3.0,2.0,0.0,14.1083
435,0.0,0.0,1.0,1.0,0.0,14.000000,1.0,1.0,2.0,120.0000
102,0.0,0.0,1.0,0.0,1.0,21.000000,1.0,0.0,1.0,77.2875