In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer

In [5]:
df=pd.read_csv("titanic_toy.csv")

In [7]:
df.head()

    Age     Fare  Family  Survived
0  22.0   7.2500       1         0
1  38.0  71.2833       1         1
2  26.0   7.9250       0         1
3  35.0  53.1000       1         1
4  35.0   8.0500       0         0

In [10]:
df.isnull().sum()

Age         177
Fare         45
Family        0
Survived      0
dtype: int64

In [9]:
x=df.drop(columns=["Survived"])
y=df["Survived"]

    
    
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [12]:
si=SimpleImputer(strategy="constant",fill_value=99)
si1=SimpleImputer(strategy="constant",fill_value=999)

In [14]:
from sklearn.compose import ColumnTransformer

In [16]:
trf=ColumnTransformer([("si",si,["Age"]),
                       ("si1",si1,["Fare"])],remainder="passthrough")

In [19]:
x_train_trf=trf.fit_transform(x_train)
x_test_trf=trf.transform(x_test)

In [22]:
x_train_trf_df=pd.DataFrame(x_train_trf,columns=trf.get_feature_names_out(),index=x_train.index)

In [32]:
x_train_trf_df.sample(5)

     si__Age  si1__Fare  remainder__Family
856     45.0   164.8667                2.0
573     99.0     7.7500                0.0
158     99.0     8.6625                0.0
143     19.0     6.7500                0.0
542     11.0    31.2750                6.0

In [27]:
x_train_trf_df.isnull().sum()

si__Age              0
si1__Fare            0
remainder__Family    0
dtype: int64

In [29]:
trf.named_transformers_["si"].statistics_

array([99], dtype=object)

In [30]:
trf.named_transformers_["si1"].statistics_

array([999], dtype=object)