In [1]:
import numpy as np
import pandas as pd

In [15]:
df=pd.read_csv("customer.csv")

In [16]:
df.sample(5)

    age  gender   review education purchased
2    70  Female     Good        PG        No
14   15    Male     Poor        PG       Yes
5    31  Female  Average    School       Yes
22   18  Female     Poor        PG       Yes
9    74    Male     Good        UG       Yes

In [ ]:
#now the gender is nominal categorical data,
#and the education is ordinal categorical data.
#and review is also ordinal categorical data.
##but seem we are working on only ordinal categorical data

In [17]:
df=df.iloc[:,2:]

In [20]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [24]:
df.shape

(50, 3)

In [21]:
#NOTE:when we are working with transform ,first thing will do these you do train_test_split

In [23]:
from sklearn.model_selection import train_test_split
x=df[["review","education"]]
y=df["purchased"]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [27]:
x_train.shape,x_test.shape

((40, 2), (10, 2))

In [28]:
x_train

     review education
33     Good        PG
35     Poor    School
26     Poor        PG
34  Average    School
18     Good    School
7      Poor    School
14     Poor        PG
45     Poor        PG
48     Good        UG
29  Average        UG
15     Poor        UG
30  Average        UG
32  Average        UG
16     Poor        UG
42     Good        PG
20  Average    School
43     Poor        PG
8   Average        UG
13  Average    School
25     Good    School
5   Average    School
17     Poor        UG
40     Good    School
49     Good        UG
1      Poor        UG
12     Poor    School
37  Average        PG
24  Average        PG
6      Good    School
23     Good    School
36     Good        UG
21  Average        PG
19     Poor        PG
9      Good        UG
39     Poor        PG
46     Poor        PG
3      Good        PG
0   Average    School
47     Good        PG
44  Average        UG

In [31]:
from sklearn.preprocessing import OrdinalEncoder

oe=OrdinalEncoder(categories=[["Poor","Average","Good"],["School","UG","PG"]])

oe.fit(x_train)

x_train=oe.transform(x_train)
x_test=oe.transform(x_test)

In [36]:
x_train=pd.DataFrame(x_train,columns=["review","education"])
x_test=pd.DataFrame(x_test,columns=["review","education"])

In [37]:
x_train.head(5)

   review  education
0     2.0        2.0
1     0.0        0.0
2     0.0        2.0
3     1.0        0.0
4     2.0        0.0

In [39]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]