In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [2]:
df=pd.read_csv("Social_Network_Ads.csv")

In [3]:
df
# df.shape  #(400, 5)

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
new_df=df.iloc[:,2:]

In [5]:
new_df

     Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [6]:
from sklearn.model_selection import train_test_split

x=new_df[["Age","EstimatedSalary"]]
y=new_df["Purchased"]

In [7]:
x

     Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
395   46            41000
396   51            23000
397   50            20000
398   36            33000
399   49            36000

[400 rows x 2 columns]

In [8]:
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [9]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

In [14]:
x_train

     Age  EstimatedSalary
92    26            15000
223   60           102000
234   38           112000
232   40           107000
377   42            53000
..   ...              ...
323   48            30000
192   29            43000
117   36            52000
47    27            54000
172   26           118000

[280 rows x 2 columns]

In [11]:
x_test

     Age  EstimatedSalary
132   30            87000
309   38            50000
341   35            75000
196   30            79000
246   35            50000
..   ...              ...
216   49            65000
259   45           131000
49    31            89000
238   46            82000
343   47            51000

[120 rows x 2 columns]

In [12]:
y_train

92     0
223    1
234    0
232    1
377    0
      ..
323    1
192    0
117    0
47     0
172    0
Name: Purchased, Length: 280, dtype: int64

In [13]:
y_test

132    0
309    0
341    0
196    0
246    0
      ..
216    0
259    1
49     0
238    0
343    1
Name: Purchased, Length: 120, dtype: int64

In [18]:
x_train.shape,x_test.shape

((280, 2), (120, 2))

In [25]:
#APPLYING STANDARDIZATION

from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()
scaler.fit(x_train) # so basically here we are store mean,and sd of x_train in scaler object

#transform the train & test sets

x_train_scaled=scaler.transform(x_train)
x_test_scaled=scaler.transform(x_test)

In [34]:
scaler.mean_ # mean of x_train
scaler.scale_ # sd of x_train

array([1.01999375e+01, 3.45792870e+04])

In [38]:
x_train

     Age  EstimatedSalary
92    26            15000
223   60           102000
234   38           112000
232   40           107000
377   42            53000
..   ...              ...
323   48            30000
192   29            43000
117   36            52000
47    27            54000
172   26           118000

[280 rows x 2 columns]

In [28]:
x_train_scaled  #but here you return scaled value in numpy array format,so convert it into dataframe.

array([[-1.1631724 , -1.5849703 ],
       [ 2.17018137,  0.93098672],
       [ 0.0133054 ,  1.22017719],
       [ 0.20938504,  1.07558195],
       [ 0.40546467, -0.48604654],
       [-0.28081405, -0.31253226],
       [ 0.99370357, -0.8330751 ],
       [ 0.99370357,  1.8563962 ],
       [ 0.0133054 ,  1.24909623],
       [-0.86905295,  2.26126285],
       [-1.1631724 , -1.5849703 ],
       [ 2.17018137, -0.80415605],
       [-1.35925203, -1.46929411],
       [ 0.40546467,  2.2901819 ],
       [ 0.79762394,  0.75747245],
       [-0.96709276, -0.31253226],
       [ 0.11134522,  0.75747245],
       [-0.96709276,  0.55503912],
       [ 0.30742485,  0.06341534],
       [ 0.69958412, -1.26686079],
       [-0.47689368, -0.0233418 ],
       [-1.7514113 ,  0.3526058 ],
       [-0.67297331,  0.12125343],
       [ 0.40546467,  0.29476771],
       [-0.28081405,  0.06341534],
       [-0.47689368,  2.2901819 ],
       [ 0.20938504,  0.03449629],
       [ 1.28782302,  2.20342476],
       [ 0.79762394,  0.26584866],
       [-0.28081405,  0.15017248],
       [ 0.0133054 , -0.54388463],
       [-0.18277423,  0.15017248],
       [-0.08473441,  0.23692961],
       [ 0.0133054 , -0.25469417],
       [ 2.17018137,  1.104501  ],
       [-1.7514113 ,  0.3526058 ],
       [ 1.87606192,  0.12125343],
       [ 0.40546467, -0.13901799],
       [-1.1631724 ,  0.29476771],
       [ 0.79762394,  1.36477242],
       [-0.28081405, -0.25469417],
       [-1.65337148, -0.05226085],
       [-0.96709276, -0.74631796],
       [ 0.30742485,  0.49720103],
       [-0.08473441, -1.06442747],
       [-1.06513258,  0.58395817],
       [ 0.11134522, -0.80415605],
       [-0.96709276,  1.53828669],
       [-0.67297331,  1.39369146],
       [-1.26121221,  0.49720103],
       [-0.28081405,  0.03449629],
       [-0.08473441,  0.00557724],
       [-0.28081405, -0.89091319],
       [ 0.89566375, -1.35361793],
       [-0.28081405,  2.2323438 ],
       [ 0.99370357,  1.97207239],
       [-1.1631724 ,  0.46828198],
       [-1.26121221,  0.26584866],
       [ 1.38586284,  1.97207239],
       [ 1.28782302, -1.35361793],
       [-0.28081405, -0.28361322],
       [-0.47689368,  1.24909623],
       [-0.77101313,  1.07558195],
       [ 0.99370357, -1.06442747],
       [ 0.30742485,  0.29476771],
       [ 0.99370357,  0.75747245],
       [-0.67297331, -1.49821316],
       [-0.67297331,  0.03449629],
       [ 0.50350449,  1.71180097],
       [ 2.07214155,  0.17909152],
       [-1.94749093, -0.74631796],
       [-0.18277423,  1.39369146],
       [ 0.40546467,  0.58395817],
       [ 0.89566375, -1.1511846 ],
       [-1.1631724 , -0.775237  ],
       [ 0.20938504,  0.23692961],
       [ 0.79762394, -0.31253226],
       [ 2.07214155, -0.80415605],
       [ 0.79762394,  0.12125343],
       [-0.28081405,  0.61287722],
       [-0.96709276, -0.31253226],
       [ 0.20938504, -0.37037036],
       [ 2.07214155,  2.11666762],
       [ 1.87606192, -1.26686079],
       [ 1.38586284, -0.91983223],
       [ 0.89566375,  1.24909623],
       [ 1.48390265,  2.11666762],
       [-0.28081405, -1.23794174],
       [ 1.97410174,  0.90206768],
       [ 0.69958412, -0.71739891],
       [-1.45729185,  0.3526058 ],
       [ 0.79762394, -1.35361793],
       [ 0.40546467, -0.13901799],
       [-0.96709276,  0.41044389],
       [ 0.0133054 , -0.31253226],
       [-1.1631724 ,  0.41044389],
       [-0.86905295, -1.2090227 ],
       [-0.08473441,  0.03449629],
       [-1.55533166, -0.42820845],
       [ 0.99370357, -1.00658937],
       [ 1.09174339, -1.2090227 ],
       [ 0.0133054 , -0.13901799],
       [-1.06513258, -1.52713221],
       [ 0.79762394, -1.2090227 ],
       [ 0.99370357,  2.05882953],
       [-1.1631724 , -1.52713221],
       [-0.28081405,  0.78639149],
       [ 0.11134522, -0.31253226],
       [-1.35925203, -1.23794174],
       [-0.5749335 , -1.49821316],
       [ 0.79762394,  0.52612008],
       [-0.28081405, -0.34145131],
       [ 1.7780221 , -0.28361322],
       [ 0.89566375, -1.03550842],
       [ 0.20938504,  0.06341534],
       [-0.5749335 ,  0.87314863],
       [-1.84945111, -1.41145602],
       [-1.26121221,  0.58395817],
       [-0.28081405,  0.52612008],
       [-0.96709276, -1.09334651],
       [ 1.1897832 , -1.44037507],
       [ 0.20938504, -0.31253226],
       [ 1.1897832 , -0.74631796],
       [-0.28081405,  0.06341534],
       [ 0.20938504,  2.08774857],
       [ 0.79762394, -1.09334651],
       [ 0.11134522,  0.03449629],
       [-1.7514113 ,  0.12125343],
       [-0.86905295,  0.15017248],
       [-0.67297331,  0.17909152],
       [ 0.89566375, -1.29577984],
       [ 0.20938504, -0.25469417],
       [-0.37885386,  1.22017719],
       [ 0.0133054 ,  0.29476771],
       [ 0.40546467,  0.15017248],
       [ 0.89566375, -0.65956082],
       [ 0.11134522,  0.15017248],
       [-1.84945111, -1.29577984],
       [-0.08473441,  0.29476771],
       [-0.18277423, -0.28361322],
       [ 0.30742485, -0.51496559],
       [-0.18277423,  1.59612479],
       [ 0.99370357, -1.18010365],
       [-0.18277423,  1.62504383],
       [ 1.28782302,  1.8563962 ],
       [-1.06513258, -0.37037036],
       [ 0.0133054 ,  0.03449629],
       [ 0.11134522, -0.25469417],
       [-1.55533166, -1.23794174],
       [-0.47689368, -0.28361322],
       [ 0.99370357,  0.12125343],
       [ 1.97410174, -1.35361793],
       [ 1.48390265,  0.06341534],
       [-0.5749335 ,  1.36477242],
       [ 1.58194247,  0.00557724],
       [-0.77101313,  0.29476771],
       [ 1.97410174,  0.7285534 ],
       [-1.1631724 , -0.51496559],
       [ 0.69958412,  0.26584866],
       [-1.35925203, -0.42820845],
       [ 0.20938504,  0.15017248],
       [-0.47689368, -1.2090227 ],
       [ 0.6015443 ,  2.00099143],
       [-1.55533166, -1.49821316],
       [-0.47689368, -0.54388463],
       [ 0.50350449,  1.82747716],
       [-1.35925203, -1.09334651],
       [ 0.79762394, -1.38253697],
       [-0.28081405, -0.42820845],
       [ 1.58194247,  0.98882482],
       [ 0.99370357,  1.42261051],
       [-0.28081405, -0.48604654],
       [-0.08473441,  2.14558666],
       [-1.45729185, -0.11009894],
       [-0.08473441,  1.94315334],
       [-0.67297331, -0.34145131],
       [-0.47689368, -0.8330751 ],
       [ 0.69958412, -1.38253697],
       [-0.77101313, -1.5849703 ],
       [-1.84945111, -1.46929411],
       [ 1.09174339,  0.12125343],
       [ 0.11134522,  1.50936765],
       [-0.28081405,  0.09233438],
       [ 0.11134522,  0.03449629],
       [-1.35925203, -1.35361793],
       [ 0.30742485,  0.06341534],
       [-0.86905295,  0.38152485],
       [ 1.58194247, -1.26686079],
       [-0.28081405, -0.74631796],
       [-0.08473441,  0.15017248],
       [-0.86905295, -0.65956082],
       [-0.67297331, -0.05226085],
       [ 0.40546467, -0.45712749],
       [-0.77101313,  1.88531525],
       [ 1.38586284,  1.27801528],
       [ 1.1897832 , -0.97767033],
       [ 1.7780221 ,  1.82747716],
       [-0.86905295, -0.25469417],
       [-0.77101313,  0.55503912],
       [-1.1631724 , -1.55605125],
       [-0.47689368, -1.12226556],
       [ 0.30742485,  0.06341534],
       [-0.18277423, -1.06442747],
       [ 1.67998229,  1.59612479],
       [ 0.99370357,  1.76963906],
       [ 0.30742485,  0.03449629],
       [-0.77101313, -0.22577513],
       [-0.08473441,  0.06341534],
       [ 0.30742485, -0.19685608],
       [ 1.97410174, -0.65956082],
       [-0.77101313,  1.33585337],
       [-1.7514113 , -0.60172273],
       [-0.08473441,  0.12125343],
       [ 0.30742485, -0.31253226],
       [ 1.09174339,  0.55503912],
       [-0.96709276,  0.26584866],
       [ 1.48390265,  0.3526058 ],
       [ 0.20938504, -0.37037036],
       [ 2.17018137, -1.03550842],
       [-0.28081405,  1.104501  ],
       [-1.65337148,  0.06341534],
       [ 0.0133054 ,  0.03449629],
       [ 0.11134522,  1.04666291],
       [-0.08473441, -0.37037036],
       [-1.1631724 ,  0.06341534],
       [-0.28081405, -1.35361793],
       [ 1.58194247,  1.104501  ],
       [-0.77101313, -1.52713221],
       [ 0.11134522,  1.8563962 ],
       [-0.86905295, -0.775237  ],
       [-0.47689368, -0.775237  ],
       [-0.28081405, -0.91983223],
       [ 0.30742485, -0.71739891],
       [ 0.30742485,  0.06341534],
       [ 0.11134522,  1.8563962 ],
       [-1.06513258,  1.94315334],
       [-1.65337148, -1.55605125],
       [-1.1631724 , -1.09334651],
       [-0.67297331, -0.11009894],
       [ 0.11134522,  0.09233438],
       [ 0.30742485,  0.26584866],
       [ 0.89566375, -0.57280368],
       [ 0.30742485, -1.1511846 ],
       [-0.08473441,  0.67071531],
       [ 2.17018137, -0.68847986],
       [-1.26121221, -1.38253697],
       [-0.96709276, -0.94875128],
       [ 0.0133054 , -0.42820845],
       [-0.18277423, -0.45712749],
       [-1.7514113 , -0.97767033],
       [ 1.7780221 ,  0.98882482],
       [ 0.20938504, -0.37037036],
       [ 0.40546467,  1.104501  ],
       [-1.7514113 , -1.35361793],
       [ 0.20938504, -0.13901799],
       [ 0.89566375, -1.44037507],
       [-1.94749093,  0.46828198],
       [-0.28081405,  0.26584866],
       [ 1.87606192, -1.06442747],
       [-0.37885386,  0.06341534],
       [ 1.09174339, -0.89091319],
       [-1.06513258, -1.12226556],
       [-1.84945111,  0.00557724],
       [ 0.11134522,  0.26584866],
       [-1.1631724 ,  0.32368675],
       [-1.26121221,  0.29476771],
       [-0.96709276,  0.43936294],
       [ 1.67998229, -0.89091319],
       [ 1.1897832 ,  0.52612008],
       [ 1.09174339,  0.52612008],
       [ 1.38586284,  2.31910094],
       [-0.28081405, -0.13901799],
       [ 0.40546467, -0.45712749],
       [-0.37885386, -0.775237  ],
       [-0.08473441, -0.51496559],
       [ 0.99370357, -1.1511846 ],
       [-0.86905295, -0.775237  ],
       [-0.18277423, -0.51496559],
       [-1.06513258, -0.45712749],
       [-1.1631724 ,  1.39369146]])

In [36]:
x_train_scaled=pd.DataFrame(x_train_scaled,columns=x_train.columns)

In [40]:
x_train_scaled

          Age  EstimatedSalary
0   -1.163172        -1.584970
1    2.170181         0.930987
2    0.013305         1.220177
3    0.209385         1.075582
4    0.405465        -0.486047
..        ...              ...
275  0.993704        -1.151185
276 -0.869053        -0.775237
277 -0.182774        -0.514966
278 -1.065133        -0.457127
279 -1.163172         1.393691

[280 rows x 2 columns]

In [45]:
x_train.describe()  # here you can see the mean and sd of x_train before scaling

#or you can round all values to 1 decimal place
# np.round(x_train.describe(),1)

              Age  EstimatedSalary
count  280.000000       280.000000
mean    37.864286     69807.142857
std     10.218201     34641.201654
min     18.000000     15000.000000
25%     30.000000     43000.000000
50%     37.000000     70500.000000
75%     46.000000     88000.000000
max     60.000000    150000.000000

In [54]:
x_train_scaled.describe()  
#so here mean is e^-17 mean 0.0000000000000000348 Basically 0 and sd is 1.0

                Age  EstimatedSalary
count  2.800000e+02     2.800000e+02
mean   3.489272e-17     6.344132e-17
std    1.001791e+00     1.001791e+00
min   -1.947491e+00    -1.584970e+00
25%   -7.710131e-01    -7.752370e-01
50%   -8.473441e-02     2.003677e-02
75%    7.976239e-01     5.261201e-01
max    2.170181e+00     2.319101e+00

In [ ]:
np.round(x_train_scaled.describe(),1)  #

         Age  EstimatedSalary
count  280.0            280.0
mean     0.0              0.0
std      1.0              1.0
min     -1.9             -1.6
25%     -0.8             -0.8
50%     -0.1              0.0
75%      0.8              0.5
max      2.2              2.3